/** Recipe hero images sourced from christmas-cracker-2026.netlify.app (cached under public/cracker/recipes). */

const RECIPE_IMAGES: Record<string, string> = {
  'Apple-Cinnamon Microwave Breakfast Bread': '/cracker/recipes/016-apple-cinnamon-microwave-breakfast-bread.jpg',
  'Banana, Ricotta & Cinnamon Breakfast Crepes': '/cracker/recipes/079-banana-ricotta-cinnamon-breakfast-crepes.jpg',
  'Banana, Ricotta & Walnut Breakfast Muffins': '/cracker/recipes/073-banana-ricotta-walnut-breakfast-muffins.jpg',
  'Beef & Bean Chilli with Crispy Baked Potato': '/cracker/recipes/069-beef-bean-chilli-with-crispy-baked-potato.jpg',
  'Beef & Lentil Curry Rice Bowl': '/cracker/recipes/062-beef-lentil-curry-rice-bowl.jpg',
  'Beef & Lentil Shepherd’s Pie with Sweet Potato Top': '/cracker/recipes/054-beef-lentil-shepherd-s-pie-with-sweet-potato-top.jpg',
  'Beef Kofta, Hummus & Couscous Plate': '/cracker/recipes/089-beef-kofta-hummus-couscous-plate.jpg',
  'Berry Cheesecake Chia Breakfast Pot': '/cracker/recipes/data-berry-cheesecake-chia-breakfast-pot.jpg',
  'Berry Ricotta French Toast': '/cracker/recipes/002-berry-ricotta-french-toast.jpg',
  'Blueberry-Lemon Ricotta Pancakes': '/cracker/recipes/088-blueberry-lemon-ricotta-pancakes.jpg',
  'Blueberry-Lemon SUPERHUMAN Bircher Muesli': '/cracker/recipes/data-blueberry-lemon-superhuman-bircher-muesli.jpg',
  'Breakfast Quesadilla with Egg, Black Beans, Spinach & Salsa': '/cracker/recipes/052-breakfast-quesadilla-with-egg-black-beans-spinach-salsa.jpg',
  'Carrot Cake Breakfast Pot': '/cracker/recipes/035-carrot-cake-breakfast-pot.jpg',
  'Cheeseburger Loaded Sweet Potato': '/cracker/recipes/036-cheeseburger-loaded-sweet-potato.jpg',
  'Cheeseburger Salad with Crispy Sweet Potato': '/cracker/recipes/034-cheeseburger-salad-with-crispy-sweet-potato.jpg',
  'Cherry-Almond Ricotta Breakfast Bowl with Toasted Oats': '/cracker/recipes/099-cherry-almond-ricotta-breakfast-bowl-with-toasted-oats.jpg',
  'Chicken Fajita Tray Bake with Rice, Avocado & Lime': '/cracker/recipes/110-chicken-fajita-tray-bake-with-rice-avocado-lime.jpg',
  'Chicken Pesto Pasta Salad': '/cracker/recipes/019-chicken-pesto-pasta-salad.jpg',
  'Chicken Risotto Lunch Box': '/cracker/recipes/086-chicken-risotto-lunch-box.jpg',
  'Chicken, Avocado & Corn Rice Salad': '/cracker/recipes/075-chicken-avocado-corn-rice-salad.jpg',
  'Chicken, Pumpkin & Spinach Risotto': '/cracker/recipes/084-chicken-pumpkin-spinach-risotto.jpg',
  'Chicken, Vegetable & Barley Soup with Toast': '/cracker/recipes/093-chicken-vegetable-barley-soup-with-toast.jpg',
  'Chocolate-Cherry SUPERHUMAN Baked Oats': '/cracker/recipes/049-chocolate-cherry-superhuman-baked-oats.jpg',
  'Cinnamon Scroll SUPERHUMAN Yoghurt Bowl': '/cracker/recipes/023-cinnamon-scroll-superhuman-yoghurt-bowl.jpg',
  'Corn, Spinach & Feta Egg Muffins with Tomato & Toast': '/cracker/recipes/data-corn-spinach-feta-egg-muffins-with-tomato-toast.jpg',
  'Cottage Cheese, Spinach & Herb Pancakes with Tomato Salsa': '/cracker/recipes/107-cottage-cheese-spinach-herb-pancakes-with-tomato-salsa.jpg',
  'Creamy Chicken Pasta Lunch Box': '/cracker/recipes/028-creamy-garlic-chicken-mushroom-pasta.jpg',
  'Creamy Garlic Chicken & Mushroom Pasta': '/cracker/recipes/028-creamy-garlic-chicken-mushroom-pasta.jpg',
  'Creamy Indian Coconut Chicken Curry': '/cracker/recipes/009-creamy-indian-coconut-chicken-curry.jpg',
  'Creamy Tomato Salmon Pasta with Spinach': '/cracker/recipes/090-creamy-tomato-salmon-pasta-with-spinach.jpg',
  'Creamy Tomato White Fish with Cannellini Beans & Greens': '/cracker/recipes/046-creamy-tomato-white-fish-with-cannellini-beans-greens.jpg',
  'Crispy Chickpea, Pumpkin & Feta Couscous Salad': '/cracker/recipes/047-crispy-chickpea-pumpkin-feta-couscous-salad.jpg',
  'Crispy Fish Tacos with Lime Slaw': '/cracker/recipes/001-crispy-fish-tacos-with-lime-slaw.jpg',
  'Crispy Lemon Salmon with Herby Couscous & Greens': '/cracker/recipes/data-crispy-lemon-salmon-with-herby-couscous-greens.jpg',
  'Crispy Tofu Satay Rice Bowl with Greens': '/cracker/recipes/104-crispy-tofu-satay-rice-bowl-with-greens.jpg',
  'Crispy Tuna & Corn Patties with Crunchy Slaw': '/cracker/recipes/109-crispy-tuna-corn-patties-with-crunchy-slaw.jpg',
  'Crunchy Chickpea, Egg & Avocado Salad Wrap': '/cracker/recipes/105-crunchy-chickpea-egg-avocado-salad-wrap.jpg',
  'Crunchy Thai Tofu & Edamame Rice Salad': '/cracker/recipes/083-crunchy-thai-tofu-edamame-rice-salad.jpg',
  'Crunchy Tuna Sushi-Style Rice Bowl': '/cracker/recipes/data-crunchy-tuna-sushi-style-rice-bowl.jpg',
  'Fresh Curry Bowl': '/cracker/recipes/011-fresh-curry-bowl.jpg',
  'Garlic Prawn & Egg Fried Rice': '/cracker/recipes/051-garlic-prawn-egg-fried-rice.jpg',
  'Garlic-Lime Prawn Tacos with Avocado Cabbage Slaw': '/cracker/recipes/072-garlic-lime-prawn-tacos-with-avocado-cabbage-slaw.jpg',
  'Greek Chicken Crunch Wrap or Bowl': '/cracker/recipes/data-greek-chicken-crunch-wrap-or-bowl.jpg',
  'Greek Lamb Souvlaki Plates': '/cracker/recipes/048-greek-lamb-souvlaki-plates.jpg',
  'Greek Turkey Meatball & Orzo Salad': '/cracker/recipes/103-greek-turkey-meatball-orzo-salad.jpg',
  'Greek Turkey Meatballs with Lemon Orzo & Tzatziki': '/cracker/recipes/101-greek-turkey-meatballs-with-lemon-orzo-tzatziki.jpg',
  'Greek-Style Garlic & Oregano Chicken Tray Bake': '/cracker/recipes/data-greek-style-garlic-oregano-chicken-tray-bake.jpg',
  'Honey-Mustard Salmon with Crispy Potatoes & Greens': '/cracker/recipes/004-honey-mustard-salmon-with-crispy-potatoes-greens.jpg',
  'Italian White Bean, Beef & Vegetable Minestrone': '/cracker/recipes/074-italian-white-bean-beef-vegetable-minestrone.jpg',
  'Lamb & Tzatziki Pita Box': '/cracker/recipes/050-lamb-tzatziki-pita-box.jpg',
  'Lamb & Vegetable Stuffed Capsicums with Herby Rice': '/cracker/recipes/005-lamb-vegetable-stuffed-capsicums-with-herby-rice.jpg',
  'Leftover Fish Taco Crunch Bowl': '/cracker/recipes/024-leftover-fish-taco-crunch-bowl.jpg',
  'Lemon Cheesecake Breakfast Pot': '/cracker/recipes/data-lemon-cheesecake-breakfast-pot.jpg',
  'Lemon Chicken & Hummus Pita or Plate': '/cracker/recipes/042-lemon-chicken-hummus-pita-or-plate.jpg',
  'Lemon Tuna, Roast Pumpkin & Couscous Plate': '/cracker/recipes/092-lemon-tuna-roast-pumpkin-couscous-plate.jpg',
  'Lemon-Caper White Fish with Warm Sweet Potato, Tomato & Green Bean Salad': '/cracker/recipes/098-lemon-caper-white-fish-with-warm-sweet-potato-tomato-green-bean-salad.jpg',
  'Lemon-Garlic White Fish with Roast Vegetables': '/cracker/recipes/037-lemon-garlic-white-fish-with-roast-vegetables.jpg',
  'Lemon-Herb Chicken with Rice & Roast Vegetables': '/cracker/recipes/040-lemon-herb-chicken-with-rice-roast-vegetables.jpg',
  'Lemon-Herb Turkey, Roast Vegetable & Couscous Bowl': '/cracker/recipes/094-lemon-herb-turkey-roast-vegetable-couscous-bowl.jpg',
  'Lemon-Poppy SUPERHUMAN Microwave Breakfast Cake': '/cracker/recipes/102-lemon-poppy-superhuman-microwave-breakfast-cake.jpg',
  'Lemongrass Chicken Rice Bowl': '/cracker/recipes/108-lemongrass-chicken-rice-bowl.jpg',
  'Lime-Sesame Prawn Rice Noodle Salad': '/cracker/recipes/053-lime-sesame-prawn-rice-noodle-salad.jpg',
  'Loaded Chilli Stuffed Sweet Potato': '/cracker/recipes/071-loaded-chilli-stuffed-sweet-potato.jpg',
  'Loaded Mexican Leftovers — Bowl, Wrap or Stuffed Potato/Sweet Potato': '/cracker/recipes/007-loaded-mexican-leftovers-bowl-wrap-or-stuffed-potato-sweet-potato.jpg',
  'Mango-Lime SUPERHUMAN Breakfast Smoothie Bowl': '/cracker/recipes/data-mango-lime-superhuman-breakfast-smoothie-bowl.jpg',
  'Mediterranean Chicken & Avocado Pita': '/cracker/recipes/059-mediterranean-chicken-avocado-pita.jpg',
  'Mediterranean Chicken with Tomato, White Beans & Herbs': '/cracker/recipes/058-mediterranean-chicken-with-tomato-white-beans-herbs.jpg',
  'Mediterranean Tuna, White Bean & Crunch Salad': '/cracker/recipes/039-mediterranean-tuna-white-bean-crunch-salad.jpg',
  'Mediterranean Turkey, Hummus & Crunch Wrap': '/cracker/recipes/080-mediterranean-turkey-hummus-crunch-wrap.jpg',
  'Mexican Scrambled Eggs, Black Beans & Toast': '/cracker/recipes/044-mexican-scrambled-eggs-black-beans-toast.jpg',
  'Middle Eastern Beef Kofta with Herby Rice & Roast Vegetables': '/cracker/recipes/087-middle-eastern-beef-kofta-with-herby-rice-roast-vegetables.jpg',
  'Middle Eastern Chicken Kofta-Style Meatballs': '/cracker/recipes/015-middle-eastern-chicken-kofta-style-meatballs.jpg',
  'Middle Eastern Chicken Meatball & Sweet Potato Salad': '/cracker/recipes/017-middle-eastern-chicken-meatball-sweet-potato-salad.jpg',
  'Mild Beef, Lentil & Spinach Curry': '/cracker/recipes/060-mild-beef-lentil-spinach-curry.jpg',
  'Miso-Ginger Salmon with Soba Noodles & Greens': '/cracker/recipes/063-miso-ginger-salmon-with-soba-noodles-greens.jpg',
  'Moroccan Lamb & Hummus Wrap or Plate': '/cracker/recipes/027-moroccan-lamb-hummus-wrap-or-plate.jpg',
  'Moroccan Lamb, Pumpkin & Couscous Tray Bake': '/cracker/recipes/025-moroccan-lamb-pumpkin-couscous-tray-bake.jpg',
  'Mushroom, Tomato, Ricotta & Egg Breakfast Flatbread': '/cracker/recipes/064-mushroom-tomato-ricotta-egg-breakfast-flatbread.jpg',
  'PB&J SUPERHUMAN Breakfast Oats': '/cracker/recipes/029-pb-j-superhuman-breakfast-oats.jpg',
  'Peach, Vanilla & Almond SUPERHUMAN Breakfast Rice': '/cracker/recipes/082-peach-vanilla-almond-superhuman-breakfast-rice.jpg',
  'Pear, Cinnamon & Vanilla SUPERHUMAN Overnight Oats': '/cracker/recipes/data-pear-cinnamon-vanilla-superhuman-overnight-oats.jpg',
  'Pork, Cucumber & Herb Rice Noodle Salad': '/cracker/recipes/097-pork-cucumber-herb-rice-noodle-salad.jpg',
  'Prawn, Corn & Black Bean Rice Salad': '/cracker/recipes/data-prawn-corn-black-bean-rice-salad.jpg',
  'Raspberry-Coconut SUPERHUMAN Chia Oats': '/cracker/recipes/067-raspberry-coconut-superhuman-chia-oats.jpg',
  'Rich Italian Beef, Mushroom & Lentil Bolognese': '/cracker/recipes/018-rich-italian-beef-mushroom-lentil-bolognese.jpg',
  'Roast Tomato, Spinach & Egg Breakfast Pita': '/cracker/recipes/076-roast-tomato-spinach-egg-breakfast-pita.jpg',
  'Roast Vegetable, Feta, Pumpkin Seed & Quinoa Lunch Box': '/cracker/recipes/057-roast-vegetable-feta-pumpkin-seed-quinoa-lunch-box.jpg',
  'SUPERHUMAN Banana-Cinnamon Protein Pancakes': '/cracker/recipes/data-superhuman-banana-cinnamon-protein-pancakes.jpg',
  'SUPERHUMAN Chocolate-Banana Breakfast Smoothie Bowl': '/cracker/recipes/026-superhuman-chocolate-banana-breakfast-smoothie-bowl.jpg',
  'Salmon Sushi Bowl': '/cracker/recipes/008-salmon-sushi-bowl.jpg',
  'Salmon, Edamame & Soba Noodle Salad': '/cracker/recipes/065-salmon-edamame-soba-noodle-salad.jpg',
  'Salmon, Potato & Green Bean Lunch Plate': '/cracker/recipes/077-salmon-potato-green-bean-lunch-plate.jpg',
  'Savoury Beef, Tomato & Avocado Breakfast Toast': '/cracker/recipes/021-savoury-beef-tomato-avocado-breakfast-toast.jpg',
  'Savoury Corn, Zucchini & Egg Breakfast Bowl': '/cracker/recipes/085-savoury-corn-zucchini-egg-breakfast-bowl.jpg',
  'Sesame Beef Crunch Wrap or Bowl': '/cracker/recipes/014-sesame-beef-crunch-wrap-or-bowl.jpg',
  'Sesame Beef Noodle Lunchbox': '/cracker/recipes/045-sesame-beef-noodle-lunchbox.jpg',
  'Slow Beef, Mushroom & Vegetable Ragu with Pasta': '/cracker/recipes/078-slow-beef-mushroom-vegetable-ragu-with-pasta.jpg',
  'Smashed Pea, Feta & Poached Egg Toast': '/cracker/recipes/096-smashed-pea-feta-poached-egg-toast.jpg',
  'Smoky Baked Beans, Spinach & Avocado on Toast': '/cracker/recipes/055-smoky-baked-beans-spinach-avocado-on-toast.jpg',
  'Smoky Mexican Beef Burrito Bowls': '/cracker/recipes/006-smoky-mexican-beef-burrito-bowls.jpg',
  'Smoky Mushroom, Spinach & Avocado Eggs on Toast': '/cracker/recipes/data-smoky-mushroom-spinach-avocado-eggs-on-toast.jpg',
  'Spanish Chicken & Roast Vegetable Lunch Plate': '/cracker/recipes/066-spanish-style-chicken-potato-vegetable-bake.jpg',
  'Spanish-Style Chicken, Potato & Vegetable Bake': '/cracker/recipes/066-spanish-style-chicken-potato-vegetable-bake.jpg',
  'Spiced Chickpea Breakfast Pancake with Fresh Tomato Salsa & Fried Egg': '/cracker/recipes/013-spiced-chickpea-breakfast-pancake-with-fresh-tomato-salsa-fried-egg.jpg',
  'Spinach, Mushroom & Feta Baked Omelette with Toast': '/cracker/recipes/data-spinach-mushroom-feta-baked-omelette-with-toast.jpg',
  'Spinach, Tomato & Feta Egg Wrap': '/cracker/recipes/038-spinach-tomato-feta-egg-wrap.jpg',
  'Sticky Asian Chicken Wings with Sesame Slaw & Rice': '/cracker/recipes/031-sticky-asian-chicken-wings-with-sesame-slaw-rice.jpg',
  'Sticky Chicken Crunch Bowl': '/cracker/recipes/033-sticky-chicken-crunch-bowl.jpg',
  'Sticky Garlic, Ginger & Sesame Beef Stir-Fry': '/cracker/recipes/012-sticky-garlic-ginger-sesame-beef-stir-fry.jpg',
  'Sticky Ginger-Sesame Salmon': '/cracker/recipes/data-sticky-ginger-sesame-salmon.jpg',
  'Strawberry-Vanilla SUPERHUMAN Breakfast Oats': '/cracker/recipes/data-strawberry-vanilla-superhuman-breakfast-oats.jpg',
  'Sweet Potato Rosti with Poached Eggs & Spinach': '/cracker/recipes/070-sweet-potato-rosti-with-poached-eggs-spinach.jpg',
  'Teriyaki Beef & Broccoli Noodles': '/cracker/recipes/043-teriyaki-beef-broccoli-noodles.jpg',
  'Thai Chicken Rice Noodle Salad': '/cracker/recipes/022-thai-chicken-rice-noodle-salad.jpg',
  'Thai Coconut Prawn Noodle Soup': '/cracker/recipes/081-thai-coconut-prawn-noodle-soup.jpg',
  'Thai-Style Lime & Coconut Chicken': '/cracker/recipes/020-thai-style-lime-coconut-chicken.jpg',
  'Tomato, Feta & Herb Baked Eggs': '/cracker/recipes/032-tomato-feta-herb-baked-eggs.jpg',
  'Tuna Niçoise-Style Lunch Plate': '/cracker/recipes/100-tuna-ni-oise-style-lunch-plate.jpg',
  'Vanilla Ricotta, Kiwi & Toasted Coconut Bowl': '/cracker/recipes/010-vanilla-ricotta-kiwi-toasted-coconut-bowl.jpg',
  'Vietnamese Lemongrass Chicken with Rice & Cucumber Salad': '/cracker/recipes/106-vietnamese-lemongrass-chicken-with-rice-cucumber-salad.jpg',
  'Vietnamese-Style Pork & Rice Bowls with Quick Pickled Vegetables': '/cracker/recipes/095-vietnamese-style-pork-rice-bowls-with-quick-pickled-vegetables.jpg',
  'Warm Apple, Cinnamon & Pecan Breakfast Quinoa': '/cracker/recipes/061-warm-apple-cinnamon-pecan-breakfast-quinoa.jpg',
  'Warm Beef & Lentil Roast-Vegetable Salad': '/cracker/recipes/056-warm-beef-lentil-roast-vegetable-salad.jpg',
  'Warm Cinnamon Apple, Egg & Oat Breakfast Bake': '/cracker/recipes/091-warm-cinnamon-apple-egg-oat-breakfast-bake.jpg',
  'Warm Pear, Walnut & SUPERHUMAN Quinoa Breakfast Bowl': '/cracker/recipes/041-warm-pear-walnut-superhuman-quinoa-breakfast-bowl.jpg',
  'Zucchini, Corn & Feta Fritters with Eggs': '/cracker/recipes/003-zucchini-corn-feta-fritters-with-eggs.jpg',
};

export function crackerRecipeImage(title: string): string | undefined {
  return RECIPE_IMAGES[title];
}

